image:
  file: .config/.gitpod.Dockerfile
tasks:
  - init: mv /workspace.old/* /workspace/ && export DISPLAY=:0 && [ ! -e /tmp/.X0-lock ] && (/usr/bin/start-vnc-session.sh &> /tmp/display-\${DISPLAY}.log)
    command: rm -f /workspace/home/databases/pgsql_data/postmaster.pid /workspace/home/databases/pgsql_data/.s.PGSQL.5432.lock && /usr/lib/postgresql/11/bin/pg_ctl start && cp .config/.apache2/apache2.conf /etc/apache2 && apachectl start && clear
ports:
  - port: 8080
    onOpen: open-browser
    visibility: private
  - port: 5432
    onOpen: ignore
    visibility: private
  - port: 5900
    onOpen: ignore
    visibility: private
  - port: 6080
    onOpen: open-browser
    visibility: private
github:
  prebuilds:
    master: true